# 모델/데이터 경로/출력 경로 설정
model_type: "llama"
model_name_or_path: "beomi/KoAlpaca-llama-1-7b"
train_data_dir: "data/json_files/*.json"
output_dir: "./checkpoints/llama"
output_model_dir: "output_dir/llama/model"
output_token_dir: "output_dir/llama/token"

# 학습 설정
batch_size: 1
epochs: 1
learning_rate: 0.0002
seed: 42
max_length: 128
split_size: 0.0015

#LoRA 설정
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
